# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import userena.managers


class Migration(migrations.Migration):

    dependencies = [
        ('userena', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userenasignup',
            managers=[
                ('objects', userena.managers.UserenaManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userenasignup',
            name='email_unconfirmed',
            field=models.EmailField(blank=True, help_text='Temporary email address when the user requests an email change.', max_length=254, verbose_name='unconfirmed email address'),
        ),
    ]
